### PR TITLE
Fix/#6610 submission window job reminder notification

### LINKED ISSUE #6610: Emission Windows Job: Quartz Job and Recipient List Changes, And Job Testing
## Continuation Of

- #4475 
- #5826
- #6241

From issues in [easey-quartz-scheduler PR #207](https://github.com/US-EPA-CAMD/easey-quartz-scheduler/pull/207)
- Previous changes in branch [feat/#4475-#5826-#6241-SubmissionWindowQrtzJob](https://github.com/US-EPA-CAMD/easey-quartz-scheduler/tree/feat/%234475-%235826-%236241-SubmissionWindowQrtzJob)

## Emission Windows Overview

Unlike monitoring plan and QA submissions, the submission of emissions occur within defined time windows.  An initial submission window is created for each monitoring plan expected to submit emissions for a particular quarter  The initial window spans 30 days in the month after the submission quarter ends.  Subsequent windows are manually created to allow the resubmission of emission reports for specific monitoring plan and reporting period combinations.  The Emissions Windows Job handles the opening of initial submission windows, the closing of resubmission windows, and sending notification emails about windows.

## Review and Test the INIT_AND_CLOSE_EM_SUBMISSION_ACCESS implementation

The INIT_AND_CLOSE_EM_SUBMISSION_ACCESS stored procedure is the core of the Emission Windows Job process.  There are several issues that need to be addressed including multiple versions of the SP.

1. The **INIT_AND_CLOSE_EM_SUBMISSION_ACCESS SP** in **camdecmpsaux** seems to have most of the functionality contained in the original Oracle version of the SP.
   - Ensure that this version correctly implements all of the Oracle functionality.
   - This version produces email events when the following occur by calling **add_window_email**.
     - 151: **No Submission Reminder Email** (on the 20th of the reporting month)
     - 152: **Critical Level 1 Submitted Reminder Email** (on the 20th of the reporting month)
     - 155: **Open Initial EM Submission Window** (at the beginning of the reporting month)
     - 156: **Outstanding Emissions Submission Reminder** (on the 20th of the reporting month)
     - 157: **Emissions Resubmission Window Closed for Non-Submitters** (After submission window ends)
   - **add_window_email** also stores the following values for use as plugin values in email templates.
     - locationList
     - orisCode
     - periodAbbreviation
     - plantName
     - plantState
     - windowOpenDate
   - The Email handling is discussed below.
   - Assume that this version of the SP was not fully tested.
2. After **review** the **camdecmps** versions of the SP and eventually **remove** them.

### The Email Processing Steps (Background from May 2024)

1. The **Emission Windows Job** initiates emails by adding a row to the camdecmpsaux **EMAIL_TO_PROCESS** table.
2. **Processing Submission Reminder Queue steps** (SubmissionReminderProcessQueue) & **Submission Window Queue** (SubmissionWindowProcessQueue).
   1. Pull needed emails from **EMAIL_TO_PROCESS** table where **EMAIL_TYPE** equals '**submissionReminder**' or '**submissionWindow**' depending on the method, and **STATUS_CD** equals '**QUEUED**'.
   2. Mark the **EMAIL_TO_PROCESS** rows' Status Codes as '**WIP**' for 'Work-In-Progress'.
   3. Get the list of **Fac Ids** for the **EMAIL_TO_PROCESS** rows.
   4. Call **CAMD-Services/support/email/emailRecipientList** with the **list of Fac Ids** and an **Email Type** of EMAIL_TYPE to get the per facility list of (To) recipients for the emails.
      -  **Needed Change 4**: This endpoint, which apparently has not been implemented, should call the CBS Recipient List endpoint to actually get the recipient list.
   5. **Needed Change 4**: Use results from the emailRecipientList endpoint to determine the email addresses for each facility.
   6. For the Fac Id for each EMAIL_TO_PROCESS row produce an EMAIL_TO_SEND row.
      1. Use Configuration["EASEY_QUARTZ_SCHEDULER_WINDOW_NOTIFICATION_FROM_EMAIL"] to determine the From address which should be the 'ECMPS Submission From Address'.
      2. **Needed Change 1**: Add an environment variables to store the **ECMPS Support email address**, and **include it as a To address**.
      3. Use the **EMAIL_TO_PROCESS.EVENT_CD** as the **TEMPLATE_ID**.
         - **Needed Change 3**: The camdecmpsaux.**EMAIL_TEMPLATE** table should contain a row for each TEMPLATE_ID that contains the **Subject Line** and the **path to the Email Body Template HTML** in the "**current**" **environment**'s EASEY_CONTENT folder.
         - **Needed Change 2**: The "**current**" **environment**'s **EASEY_CONTENT folder** should contain the **Email Body Template HTML** in the "**Templates**" **subfolder**.
      4. Set **STATUS_CD** to '"**QUEUED**'".
      5. Set **CONTEXT** to the **EMAIL_TO_PROCESS**.**CONTEXT**.
3. **Processing Email Queue steps** (EmailQueue)
   1. The "**Email Queue**" Job handles sending the emails by processing rows added to the **EMAIL_TO_SEND** table and calling "**[EASEY_CAMD_SERVICES]/support/email/process**" for each of them.
   2. Configuration["EASEY_QUARTZ_SCHEDULER_MAX_EMAILS_TO_SEND"] contains the maximum number of in-progress email jobs allowed.
   3. Determine the number of in-progress email jobs by counting the EMAIL_TO_SEND rows with STATUS_CD equals 'WIP'.
   4. Stop processing if the **maximum number** of in-progress **email jobs** are running.
   5. Pull the **next email** to send from the **EMAIL_TO_SEND** rows where **STATUS_CD** equals '**QUEUED**'.
   6. Mark the **EMAIL_TO_SEND** row's Status Code as '**WIP**' for 'Work-In-Progress'.
   7. Call **CAMD-Services/support/email/Process** with the **EMAIL_TO_SEND_ID** to send an email.
   8. Return to step 3.
4. **Sending Email steps** (MailTemplateService)
      1. Get the **EMAIL_TO_SEND** row using the passed id.
      2. Get the **EMAIL_TEMPLATE** row using the **EMAIL_TO_SEND**.**TEMPLATE_ID**.
         - **Needed Change 3**: The camdecmpsaux.**EMAIL_TEMPLATE** table, which contains the **Event Type Id** as a primary key, and includes the **email subject** and the **location of the email body template** in the **environment folders** of the **EASEY_CONTENT** repository.
         - **Needed Change 2**: The HTML in the EASEY_CONTENT repository that contains the email body template.
      3. Parse the context from the **EMAIL_TO_SEND**.**CONTEXT**.
      4. Get and **format** the **template** **using** the **context**.
      5. **Send** the **email**.
      6. **Set** the **EMAIL_TO_SEND** row's **Status Code** as '**COMPLETE**'.

### Needed Changes

1. Add an environment variable "**EASEY_ECMPS_SUPPORT_TO_EMAIL**" to store the ECMPS Support email address (if not already added).
   - Include the address in "**EASEY_ECMPS_SUPPORT_TO_EMAIL**"as a To address for the emails in both the **SubmissionReminderProcessQueue** and **SubmissionWindowProcessQueue** Execute methods. 
   - **This requirement is no longer valid. A new ticket will be created for this requirement in a future sprint. See comments on ticket #5826 ** 
2. Add email body template to the **EASEY_CONTENT** repository's "**/dev/templates**" folder for events 151, 152, 155, 156 and 157.
   - See the [Email Information comment](https://github.com/US-EPA-CAMD/easey-ui/issues/6610#issuecomment-2715212137) for email body text information.
   - The camdecmpsaux.**EMAIL_TEMPLATE** table contains rows for events 151, 152, 155, 156 and 157, and the TEMPLATE_LOCATION column indicates the name of the HTML file containing each email body template.
3. Check the camdecmpsaux.**EMAIL_TEMPLATE** table.
   - Determine whether a script is needed for the data in the camdecmpsaux.**EMAIL_TEMPLATE** table.
   - Check the subject lines in the table against the subject lines in the [Email Information comment](https://github.com/US-EPA-CAMD/easey-ui/issues/6610#issuecomment-2715212137).
4. Create the **[EASEY-CAMD-SERVICES]/support/email/emailRecipientList** endpoint to return the recipient list.  
   - The endpoint should call the CBS Email Recipients Endpoint.
     -  See the [CBS Email Recipients API Endpoint Information comment](https://github.com/US-EPA-CAMD/easey-ui/issues/6610#issuecomment-2710975628) for more details.
     - Make any needed updates to the call to **[EASEY-CAMD-SERVICES]/support/email/emailRecipientList** endpoint from the **SubmissionReminderQueue** and **SubmissionWindowQueue** jobs.
       - Ensure that the processing of the recipient list in the job's Execute method correctly parses and uses the data.
         - Based on the [CBS Email Recipients API Endpoint Information comment](https://github.com/US-EPA-CAMD/easey-ui/issues/6610#issuecomment-2710975628) the list is a a list of email addresses that each include a list of associated Facility Ids.  The handling appears to expect a list of "recipients" that contain a list of facilities that contain a list of email addresses, which I believe is incorrect.
         - Entertain centralizing the logic that reformats the recipient list, particularly if it is corrected.
5. Test the email process for each event type to ensure the emails are created as expected and logged in the API application logs as expected (similar examples are in 6086).

## Create a Quartz Job for the Emission Windows Job

The Emission Windows Job should run once a day to check for and trigger the actions it covers.  To ensure the runs occur a Quartz job is needed that calls the **INIT_AND_CLOSE_EM_SUBMISSION_ACCESS SP** in **camdecmpsaux**.

Note that the Quartz job as created in the [Submission Window Management Job pull request](https://github.com/US-EPA-CAMD/easey-quartz-scheduler/pull/207) handles the sending of emails and some actions handled by the **INIT_AND_CLOSE_EM_SUBMISSION_ACCESS SP**.  It should have handled the calling of the **INIT_AND_CLOSE_EM_SUBMISSION_ACCESS SP**.

###

### PR DESCRIPTION
**Pull request by yonatan-dp**
- new email grouping strategy
- added email creation retry logic
- added support for  note and note time fields to store error information

### CODE REVIEW

File: admin/Jobs/EmailQueueJobs/BaseEmailProcessor.cs [hunk 1]
```diff
@@ -65,7 +110,7 @@ protected async Task<Dictionary<decimal, HashSet<string>>> ProcessEmailRecipient
             {
                 string notificationTypeForDb = GetEmailTypeForDatabase();
                 
-                // Get queued emails for this type
+                // 1. Get all queued email_to_process records from database
```
Comment (mark-hayward-erg) [inline admin/Jobs/EmailQueueJobs/BaseEmailProcessor.cs]: Steps 1-6 need to be in a loop, one execution per email_to_process.event_code.  

Each event_code should result in a set of grouped emails, which will have it's own combination of recipients and facilities.

For example, the submission window job may have created a number of submissionReminder records in email_to_process, some with event_code 151 and some with event_code 152, with different recipients and/or facilities within each set.   Those sets of emails need to be grouped separately into emails to send.  The resulting emails for each of those reminder sets will also have different email text.

Example email_to_process records:

| email_type | event_code | fac_id |
| - | - | - |
| submissionReminder | 151 | 1 |
| submissionReminder | 151 | 2 |
| submissionReminder | 151 | 3 |
| submissionReminder | 151 | 4 |
| submissionReminder | 152 | 3 |
| submissionReminder | 152 | 4 |
| submissionReminder | 152 | 5 |
| submissionReminder | 152 | 6 |


Example resulting recipient API responses:

For 151 emails:

`
[
  {  
      "emailAddressList": "bob@email",  
      "plantIdList": [1,2]  
  },  
  {
      "emailAddressList": "steve@email",  
      "plantIdList": [2,3,4]  
  },  
  {
      "emailAddressList": "fred@email",  
      "plantIdList": [3]  
  },  
  {
      "emailAddressList": "jim@email",  
      "plantIdList": [4]  
  }
]
`

For 152 emails:
`
[
  {
      "emailAddressList": "steve@email",  
      "plantIdList": [3,4]  
  },  
  {
      "emailAddressList": "fred@email",  
      "plantIdList": [3]  
  },  
  {
      "emailAddressList": "jim@email",  
      "plantIdList": [4]  
  } 
  {
      "emailAddressList": "sue@email",  
      "plantIdList": [5,6]  
  }
]
`

**Review by mark-hayward-erg — CHANGES_REQUESTED** [review]

File: admin/Jobs/EmailQueueJobs/BaseEmailProcessor.cs (hunk 1 above)
Comment (yonatan-dp) [reply admin/Jobs/EmailQueueJobs/BaseEmailProcessor.cs]: Absolutely correct. Good catch 👍. Fixed and pushed.

**Review by mark-hayward-erg — APPROVED** [review]
