### PR TITLE
Fix/#7122 replace static fields and properties

### LINKED ISSUE #7122: Check Engine: Investigate Handle Changeable Static Variables and Properties
# Background

During a meeting to discuss Quartz scheduling by instance in ECMPS 2.0, it was noticed that evaluations of the same emission report did not always produce the same severity.  Based on CVP making changes to the Check Engine to store check parameters in instantiated classes and properties instead of static classes with their properties, research was performed that found the following Quartz related information.

> **Concurrency Issues**: Static properties on a static class are not inherently thread-safe in C#. If multiple instances of the job or other parts of the application access the same static variable concurrently, it can lead to data corruption or unexpected behavior unless explicit synchronization mechanisms (like locks) are used, which adds complexity. 

Additional research found the following.

> **Job Instancing**: By default, a new instance of the job class is created for each execution. This helps avoid concurrency issues within the job's internal state, but you must still synchronize access to any shared resources like static fields or singletons.

> **Immutability**: The simplest way to make a static property thread-safe is to ensure the object it holds is immutable (its state cannot be changed after creation). If the data never changes, no race conditions can occur. 

> **Stateless methods are thread-safe**: A static method that does not access any static fields (other than read-only ones initialized in the static constructor), and only uses data passed in as parameters or local variables, is inherently thread-safe. Local variables are stored on the thread's own stack, so each thread gets its own copy and they do not interfere with each other.
>
> **Methods accessing shared state are not thread-safe**: If a static method reads or modifies shared static variables (fields), multiple threads can access and modify that data concurrently, leading to race conditions and unpredictable behavior.

#### Problem Conditions

1. Static Fields that are changed after initialization.
   - This is really limited to static fields that are not read-only.
2. Static Properties that have a setter or have a getter that does not always return the same value.
3. Static Methods that access problematic static fields or properties.
   - Handling the problem static fields and properties should handle any problem static methods.

# Found Problems

### CheckEngine / SpecialParameterClasses

- Check the following for research and change details.
  - [Handling Supplemental Data Table Static Properties comment](https://github.com/US-EPA-CAMD/easey-ui/issues/7122#issuecomment-3910471619)
  - [Handling Fc Validation Info Static Properties comment](https://github.com/US-EPA-CAMD/easey-ui/issues/7122#issuecomment-3910509570)

#### ComponentOperatingSupplementalData
```
public static DataTable SupplementalDataUpdateDataTable { get; set; }
```

#### cDailyCalibrationData
```
public static DataTable SupplementalDataUpdateLocationDataTable { get; set; }
public static DataTable SupplementalDataUpdateSystemDataTable { get; set; }
```

#### FcValidationInfo
```
static public decimal? NonFuelSpecificMaxValue { get; set; }
static public decimal? NonFuelSpecificMinValue { get; set; }
```

#### LastQualityAssuredValueSupplementalData
```
public static DataTable SupplementalDataUpdateDataTable { get; set; }
```

#### QaCertificationSupplementalData
```
public static DataTable SupplementalDataUpdateDataTable { get; set; }
```

#### SamplingTrainEvalInformation
```
public static DataTable SupplementalDataUpdateDataTable { get; set; }
```

#### SystemOperatingSupplementalData
```
public static DataTable SupplementalDataUpdateDataTable { get; set; }
```
        
#### cNpgsqlServer

- Check the following for research and change details.
  - [DatabaseAccess / cDatabase / cNpgsqlServer Statics comment](https://github.com/US-EPA-CAMD/easey-ui/issues/7122#issuecomment-3921786489)

```
static private string _sDbConnectionString = null;
static private NpgsqlDataSource _sqlDataSource = null;
static private NpgsqlDataSource _sqlDataSourcePrimary = null;
static private NpgsqlDataSource _sqlDataSourceReplica = null;
static private readonly object _dataSourceLock = new object();
public static bool IsMultiHostConfigured => _sqlDataSourcePrimary != null && _sqlDataSourceReplica != null && _sqlDataSourcePrimary != _sqlDataSourceReplica;
static private bool _bStealth = false;
public static bool StealthMode { get { return _bStealth; } set { _bStealth = value; } }
static public string DbConnectionString { get { return _sDbConnectionString; } set { _sDbConnectionString = value; } }
private static DataView m_dvSeverityCode = null;
```

#### ConnectionStringManager
    
> Statics everywhere, but the values should be the same regardless of the thread that last updated them.
            
#### Properties / Property.Settings
          
- `private static ILoggerFactory _loggerFactory`  
> _loggerFactory is used to get a logger instance and should always exist, even if updated by another thread.
                    
### DM / Utilities

- Check the following for research and change details.
  - [DM Utilities and Type Utilities comment](https://github.com/US-EPA-CAMD/easey-ui/issues/7122#issuecomment-3922036119)
    
#### cCalculator
        
```
public static string ErrorDetail { get; private set; }
public static Exception TrappedException { get; private set; }
```

### TypeUtilities

- Check the following for research and change details.
  - [DM Utilities and Type Utilities comment](https://github.com/US-EPA-CAMD/easey-ui/issues/7122#issuecomment-3922036119)

#### cDateFunctions

```
private static DataTable FReportingPeriodTable = null;
```

#### cDecimalPrecision

```
private static cHandleDecimalPrecision[] FDecimalPrecision;
```
> Seem to always have the same value.  Investiage making it read-only.
    
#### DistinctHourRanges

```
public static DateTime MaxHour { get; private set; }
public static DateTime MinHour { get; private set; }
```

#### Quarter

```
private static Dictionary<int, Quarter> QuarterDictionary = new Dictionary<int, Quarter>();
```

#### cReportingPeriod

```
public static DataTable LookupTable
{
  get
  {
    if (FLookupTable == null)
    {
      try
      {
        // Using replica db: camdecmpsmd.reporting_period is read-only reference data
        cDatabase Database = cDatabase.GetConnection("cDateFunctions", cDatabase.eDatabaseTarget.READONLY);

        FLookupTable = Database.GetDataTable("select * from camdecmpsmd.reporting_period order by Calendar_Year, Quarter");
      }
      catch (Exception ex)
      {
        LoggerProvider.GetLogger<cReportingPeriod>().LogError(ex, "Error retrieving Reporting Period Lookup Table");
        FLookupTable = null;
      }
    }

    return FLookupTable;
  }

  set
  {
    FLookupTable = value;
  }
}

protected static DataTable FLookupTable = null;
```

### LoggerProvider (Used in the Check Engine)
```
private static ILoggerFactory _loggerFactory;
public static ILogger<T> GetLogger<T>() => _loggerFactory.CreateLogger<T>();
public static ILogger GetLogger(string category) => _loggerFactory.CreateLogger(category);
```

### LogHelper(Not used in the Check Engine)
```
private static ILogger logger = new LoggerFactory().CreateLogger(typeof(LogHelper));
```

# Not Covered

| Project | Comment | 
| :--- | :--- |
| CheckEngine.CheckRunner | Not part of the applications. | 
| CheckEngine.CheckParameters | All statics are methods. | 
| CheckEngine.EcmpsCommon | All statics are methods or properties that return a constant value. | 
| CheckEngine.Emissions | All statics are methods. | 
| CheckEngine.Import | Not used in ECMPS 2.0. | 
| CheckEngine.LME | Not used in ECMPS 2.0 and no statics. | 
| CheckEngine.MonitorPlan | All statics are methods. | 
| CheckEngine.QA\Processes | No statics. | 
| CheckEngine.UnitTest | Not part of the applications and not used in ECMPS 2.0. |

### PR DESCRIPTION
**Pull request by djw4erg**
## Replaced supplemental data table static properties.
1. Replaced the static properties in the various supplemental data classes with non-static properties in the emission process class.
2. Removed unused variable containing the static properties, an associated unused variable, and related commented out code.

- CheckEngine / SpecialParameterClasses
  - ComponentOperatingSupplementalData.cs
  - DailyCalibrationData.cs
  - LastQualityAssuredValueSupplementalData.cs
  - QaCertificationSupplementalData.cs
  - SamplingTrainEvalInformation.cs
  - SystemOperatingSupplementalData.cs
- Emissions / EmissionReport
  - EmissionReportProcess

## Removed static properties from FcValidationInfo class.
1. Updated HOURGEN-33 to remove setting of the static properties.
2. Updated HOURop-34 to replace use of the static properties with the existing minValue and maxValue variables.

- CheckEngine / SpecialParameterClasses
  - FcValidationInfo
- Emissions / EmissionReport / Checks
  - HourlyGeneralChecks.cs
  - HourlyOperatingDataChecks.cs
  - ReportingPeriod.cs

##  Changed Private Static Fields to Private Static Readonly Fields
- TypeUtilities
  - DistinctHourRanges.cs: Collateral changes in FormulaChecks.cs (MonitorPlan / Checks).
  - DateFunctions.cs: Collateral changes in CheckEngine.cs (CheckEngine)
  - DecimalPrecision.cs
  - Quarter.cs: Includes replacing incidental updates to QuarterDictionary with initial population.

## Remove the following static fields and associated properties and methods.
- DM / Utilities / cCalculator
  - ErrorDetail and TrappedException static properties
- DatabaseAccess / NpgsqlServer.cs / cDatabase
  - `private static DataView m_dvSeverityCode`
    - `public static string GetSeverityDescription(string ASeverityCd, string ADefault)`
    - 'public static int GetSeverityLevel(string ASeverityCd, int ADefault)'
    - 'private static DataRowView GetSeverityRow(string ASeverityCd)'
    - 'private static bool LoadSeverityCode()'
  - `static private bool _bStealth = false;`
    - `public static bool StealthMode { get { return _bStealth; } set { _bStealth = value; } }`
    - `if (_bStealth == false)` in `public bool Open()` but leaving the `Logging.LogException(_LastException, "Error Connecting to Database");`.

## Handled _sDbConnectionString static field
- DatabaseAccess / NpgsqlServer.cs / cDatabase
  1. Included locks in DbConnectionString getter and setter to place access to _sDbConnectionString in locks.
  2. Replaced references to _sDbConnectionString that are not with a lock with the DbConnectionString property.

### CODE REVIEW

File: CheckEngine/CheckEngine/SpecialParameterClasses/SamplingTrainEvalInformation.cs
Comment (yonatan-dp) [inline CheckEngine/CheckEngine/SpecialParameterClasses/SamplingTrainEvalInformation.cs]: Remove `SupplementalDataUpdateDataTable `, similar to the other patterns (no longer used)?

Also, it looks like SamplingTrainSuppDataUpdate() method in EmissionsReportProcess.cs:6028 still writes to this static property (which is no longer being written to).

File: CheckEngine/DatabaseAccess/cNpgsqlServer.cs [hunk 1]
```diff
@@ -2550,94 +2550,6 @@ public bool MigrateWorkspaceSession_QA(string chkSessionId,
 
         #endregion
 
-
-        #region Public Static Methods: Severity Code
-
-        private static DataView m_dvSeverityCode = null;
```
Comment (yonatan-dp) [inline CheckEngine/DatabaseAccess/cNpgsqlServer.cs:2556]: I see that this same pattern (that is removed here) still exists in cExtensions._dvSeverityCode (cExtensions.cs, line 28+). It is still in use (e.g. Category.cs line 615).  `cExtensions._dvSeverityCode` is also not synchronized and is mutable.  If two evaluations trigger LoadSeverityCode() concurrently, one thread can be iterating the DataView updating Blocks_Submission values (lines 142-148) while another thread is reading from it via .Find() (in one of the `GetSeverityRow` methods). It does not look like DataView is thread-safe for concurrent read/write.  

Could this be one of the reasons for the bug you described in the ticket description: "evaluations of the same emission report did not always produce the same severity..."

File: CheckEngine/DM/Utilities/cCalculator.cs
Comment (yonatan-dp) [inline CheckEngine/DM/Utilities/cCalculator.cs]: Should this also be removed? I don't see any usages for `TrappedException `

**Review by yonatan-dp — CHANGES_REQUESTED** [review]

File: CheckEngine/CheckEngine/SpecialParameterClasses/SamplingTrainEvalInformation.cs
Comment (djw4erg) [reply CheckEngine/CheckEngine/SpecialParameterClasses/SamplingTrainEvalInformation.cs]: I caught that while checking my change to the Load Data Table methods and updated.

File: CheckEngine/DatabaseAccess/cNpgsqlServer.cs (hunk 1 above)
Comment (djw4erg) [reply CheckEngine/DatabaseAccess/cNpgsqlServer.cs]: > Could this be one of the reasons for the bug you described in the ticket description: "evaluations of the same emission report did not always produce the same severity..."

I am not sure this would change the severity but possibly not return one if the data table is being updated by another thread.

**Review by yonatan-dp — APPROVED** [review]

**Review by yonatan-dp — APPROVED** [review]
