### PR TITLE
Fix/6925 duplicate check engine evaluation jobs

### LINKED ISSUE #6925: Prevent duplicate CheckEngineEvaluation jobs
During one perf test run we set the quartz maxConcurency to 10 threads per instnace and set the WIP for each of the process codes (MP, QA, EM) and submissions to 25 each.  This was to see if we could get the CheckEngineEval jobs to be more evenly spread across the instances.  While the jobs appeared to be spread more evenly, this also created a condition where CheckEngineEvaluation jobs were scheduled twice.  The root cause for this appears to be the way we are setting the eval to the 'WIP' status.  If more eval jobs are scheduled than there are available threads, Quartz will queue the job internally (in the scheduler), and they will remain in the "waiting" state until a thread is available.  Since the Eval job is not placed into the 'WIP' status until the CheckEngineEval job actually runs, this job can be scheduled again by another run of the EvaluationJobQueue job because while its waiting for a thread its still in the "QUEUED" status.

The fix for this is as soon as the EvaluationJobQueue job selects a batch of evals to start, they should be set to a status which indicates that they have been scheduled (e.g. "CLAIMED").  This would indicate that the job is scheduled but has not started, immediately making it ineligible to be picked up by another EvaluationJobQueue job.  

Here's an example of SQL that could be used to achieve this:

```sql
UPDATE camdecmpsaux.evaluation_queue
SET status_cd = 'CLAIMED'
WHERE evaluation_id IN (
    SELECT evaluation_id FROM camdecmpsaux.evaluation_queue
    WHERE process_cd = <type> AND status_cd = 'QUEUED'
    ORDER BY queued_time
    LIMIT <jobs_to_schedule>
    FOR UPDATE SKIP LOCKED
)
RETURNING *;
```

We would need to make sure that this additional status does not have any adverse impacts.  For example the Queue position logic would need to be able to handle the new status.  Anything that was in the "CLAIMED" status should still indicate "Queued #XX" on the eval screen.  Also the query that is used to determine the current amount of "WIP" would need to be updated to include anything in the 'WIP' or 'CLAIMED' status.

### PR DESCRIPTION
**Pull request by maxdiebold-erg**
## Related Issues:

- https://github.com/US-EPA-CAMD/easey-ui/issues/6925

## Main Changes:

- Updated the **`EvaluationJobQueue`** job to set evaluations to the new CLAIMED status prior to initiating a **`CheckEngineEvaluation`** job. This prevents the evaluation from being picked up again by the queue job if it runs again before the evaluation is processed.

### CODE REVIEW

File: admin/Jobs/EvaluationJobQueue.cs [hunk 1]
```diff
@@ -31,79 +31,114 @@ public async Task Execute(IJobExecutionContext context)
...
                 List<Evaluation> wip = _dbContext.Evaluations.FromSqlRaw(@"
                     SELECT *
                     FROM camdecmpsaux.evaluation_queue
-                    WHERE process_cd = {0} AND status_cd = 'WIP'
-                    ORDER BY queued_time", type
+                    WHERE process_cd = {0} AND status_cd in ('WIP', 'CLAIMED')
+                    ORDER BY queued_time", processType
                 ).ToList();
 
                 _logger.LogInformation("Found {Count} {Type} evaluations in WIP status",
```
Comment (yonatan-dp) [inline admin/Jobs/EvaluationJobQueue.cs]: Minor but will help debugging.  Log message should say WIP or CLAIMED

Comment (yonatan-dp) [reply admin/Jobs/EvaluationJobQueue.cs]: Prob rename `wip` to `wipOrClaimed`?

**Review by yonatan-dp — CHANGES_REQUESTED** [review]

File: admin/Jobs/EvaluationJobQueue.cs (hunk 1 above)
Comment (maxdiebold-erg) [reply admin/Jobs/EvaluationJobQueue.cs]: Both good calls!

**Review by yonatan-dp — APPROVED** [review]
