### PR TITLE
Fix/6798 evaluation queuing race condition

### LINKED ISSUE #6798: Race condition in evaluation queuing logic
A race condition exists in the `CheckEngineEvaluation` Quartz job that could result in an Emissions record being evaluated before a QA record it depends on is evaluated.

When a set of records is evaluated, the records are processed in the following order:

- The associated MP is evaluated first (if `submitMonPlan` is true).
- The specified QA records are evaluated in parallel.
- The specified EM records are evaluated sequentially.

At the end of a successful QA evaluation, the first EM `CAMDECMPSAUX.EVALUATION_QUEUE` record is unconditionally queued. Since QA records are evaluated in parallel, however, it could be the case that other QA evaluations are still in progress. This logic should be updated to only queue EM records when _all_ of the QA records (and implicitly the MP record) have the status code "COMPLETE".

## Acceptance Tests

- Evaluate 11 QA records and 1 EM record in a single set. All `CAMDECMPSAUX.EVALUATION_QUEUE` records with the same `evaluation_set_id` and a process code (`process_cd`) of "QA" should have a `completed_time` before the `started_time` of all records in the same set with a process code "EM".

### PR DESCRIPTION
**Pull request by maxdiebold-erg**
## Related Issues:

- https://github.com/US-EPA-CAMD/easey-ui/issues/6798

## Main Changes:

- Rather than queuing the first EM evaluation as soon as one QA evaluation finishes, wait until all QA evaluations have the `status_cd` "COMPLETE" before queuing the first EM evaluation.

### CODE REVIEW

File: admin/Jobs/CheckEngineEvaluation.cs [hunk 1]
```diff
@@ -422,6 +357,89 @@ ORDER BY eq.rpt_period_id
...
+                    }
+
+                    break;
+                case "QA":
+                    // Check that all QA evaluations have been completed before proceeding to EM evaluations.
+                    bool qaEvalsRemain = _dbContext.Evaluations
+                      .Where(eq => eq.StatusCode != "COMPLETE" && eq.ProcessCode == "QA" && eq.EvaluationSetId == es.SetId)
+                      .Any();
+
+                    if (qaEvalsRemain) break;
```
Comment (djw4erg) [inline admin/Jobs/CheckEngineEvaluation.cs:388]: What starts the next queued QA if one exists?  Should that occur here?

Comment (maxdiebold-erg) [reply admin/Jobs/CheckEngineEvaluation.cs:388]: QA records are all queued at once, after an MP evaluation (if there is one), so there's never a need for one QA eval to queue another QA eval. This block tries to queue the first EM record (since they are evaluated sequentially), but bails if all QA evaluations have not completed.

Comment (djw4erg) [reply admin/Jobs/CheckEngineEvaluation.cs:388]: Thanks and approving now.

**Review by djw4erg — DISMISSED** [review]

**Review by djw4erg — APPROVED** [review]
